language: python

python:
 - 2.7
# - 3.4

env:
  global:
  - BERKELEYDB_LIBDIR=/usr/lib/x86_64-linux-gnu BERKELEYDB_INCDIR=/usr/include

before_install:
- ssh-keygen -t rsa -C your_email@youremail.com -P '' -f ~/.ssh/id_rsa
- cat /home/travis/.ssh/id_rsa.pub >> /home/travis/.ssh/authorized_keys
- ln -s /home/travis/.ssh/authorized_keys /home/travis/.ssh/authorized_keys2
- echo "Host localhost" >> /home/travis/.ssh/config
- echo "    StrictHostKeyChecking no" >> /home/travis/.ssh/config
- chmod g-rw,o-rw /home/travis/.ssh/*

- chmod 644 ~/.bashrc
- echo "PATH=${PATH}" > ~/.bashrc

- sudo rm -f /etc/apt/sources.list.d/pgdg-source.list
- sudo rm -rf /usr/local
- echo 'yes' | sudo add-apt-repository ppa:stephane-brunner/precise
- echo 'yes' | sudo add-apt-repository ppa:mapnik/v2.2.0
- sudo apt-get update
- sudo apt-get install -y --force-yes libmapnik-dev python-mapnik apache2 cgi-mapserver deploy libdb-dev optipng postgresql-9.1-postgis-2.0=2.0.3-2~precise4 postgis=2.0.3-2~precise4

- sudo -u postgres tilecloud_chain/tests/create_test_data.sh
- sudo cp tilecloud_chain/tests/apache.conf /etc/apache2/sites-enabled/apache.conf
- sudo apache2ctl graceful

- sudo tilecloud_chain/tests/create-deploy.sh

- sudo mkdir /tmp/tests
- sudo chmod g+s,o+w /tmp/tests

install:
- pip install -r requirements.txt
- pip install -r dev-requirements.txt
- touch tilecloud_chain/OpenLayers.js

script:
- find tilecloud_chain -name \*.py | xargs flake8 --max-line-length=120
- vvv-validate-rst README.rst
- vvv-validate-rst CHANGES.rst
- python setup.py --long-description > PYPI.rst
- vvv-validate-rst PYPI.rst
- python setup.py nosetests --stop

after_failure:
- python setup.py nosetests

after_success:
# Report coverage results to coveralls.io
- pip install coveralls
- coveralls
